### PR TITLE
fix: use of hookable package instead of hable

### LINKED ISSUE #338: Use "hookable" instead of "hable" to support nuxt@2.17.3
In nuxt@2.17.3 "hable" was replaced by "hookable", see https://github.com/nuxt/nuxt/pull/24426

lib/plugins/context.js uses hable directly - this leads to problems when using nuxt-typo3 with nuxt@2.17.3. I think this must be considered in a full upgrade of nuxt-edge or can you add hookable/hable as direct dependency?

### PR DESCRIPTION
**Pull request by mateusznarowski**
fixes #338

### CODE REVIEW

File: lib/plugins/context.js [hunk 1]
```diff
@@ -1,5 +1,5 @@
 import { defu } from 'defu'
-import Hookable from 'hable'
+import Hookable from 'hookable'
```
Comment (mercs600) [inline lib/plugins/context.js:2]: there is no export default for hookable library
